### PR TITLE
whoops wrong audio fix suggested

### PR DESCRIPTION
**Pull request by eXioStorm**
I accidentally sent the wrong change in my last suggestion, this is better.
(fixes a bug with audio ending too soon)

### CODE REVIEW

**Comment by JakeStanger** [comment]
Wow I wasn't expecting to see a PR for this project. Cheers!

**Comment by eXioStorm** [comment]
when I was trying to figure out how to use openAL I read your code to help me figure out how it worked, ended up finding and fixing a bug at the same time so I figured I should offer it back here. :d (I had some help fixing the bug, though I didnt exactly find it, I knew which section of code was causing the bug. xd)

**Comment by JakeStanger** [comment]
I'm very glad to be of help! For reference, this was the tutorial book I followed for the engine, you may find it useful: https://ahbejarano.gitbook.io/lwjglgamedev/

**Comment by eXioStorm** [comment]
oh wow! I didnt come across that, thanks a bunch!

**Pull request merged**
